name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --verbose

    - name: Create build directory
      run: mkdir -p build

    - name: Copy binary to build folder
      run: cp target/release/untitled1 

    - name: Make run script executable
      run: chmod +x run.sh

    - name: Run tests
      run: cargo test --verbose 
